### ISSUE TITLE
wolfictl repo: subcommand for working with APK repositories

### ISSUE THREAD

**Issue by jdolitsky** [wolfi-dev/wolfictl#1]
Propose `wolfictl repo` which helps with working with APK repositories

Example - generate a static APK repo:
```
wolfictl repo generate <package...> [--out-dir=<dir>]
```

this would generate a repo at `<dir>` (default: `./apk-repo/`):

```
./apk-repo/APKINDEX.tar.gz
./apk-repo/packages/x86_64/brotli-1.0.9-r0.apk
./apk-repo/packages/x86_64/autoconf-2.71-r0.apk
./apk-repo/packages/x86_64/build-base-1-r3.apk
./apk-repo/packages/x86_64/busybox-1.35.0-r3.apk
./apk-repo/packages/x86_64/ca-certificates-bundle-20220614-r2.apk
...
```

Then we can enable people to host their own APK repos, by simply uploading this directory to their static host of choice. Similar to some of the things done here cc @cpanato https://github.com/helm/chart-releaser

**Comment by imjasonh** [comment]
`wolfictl generate-index` to generate based on bucket contents, `wolfictl index` to read a remote index.
