### ISSUE TITLE
Time-sensitive: Public images will be removed on 2024-11-21

### ISSUE THREAD

**Issue by jdolitsky** [wolfi-dev/wolfictl#1249]
There are upcoming changes to Chainguard Images Developer Tier that will take effect on November 21, 2024:
	https://www.chainguard.dev/unchained/changes-to-chainguard-images-developer-tier

Several public images are scheduled to be removed unless they are found on the list here:
https://support.chainguard.dev/hc/en-us/articles/28452542784667-Customer-Notice-Free-Image-Tier-Changes

Some of these images that will be removed are referenced in source files inside this repository.

For the following list, please place a check if the image is OK to remove, or if the reference has since been removed from this repository:

- [ ] `cgr.dev/chainguard/coredns`
  - [`docs/man/man1/wolfictl-image-apk.1`](https://github.com/wolfi-dev/wolfictl/blob/8c3b12965dbf2c2caa18b6a4ebd667c3a2d33108/docs/man/man1/wolfictl-image-apk.1)
  - [`pkg/cli/image_apk.go`](https://github.com/wolfi-dev/wolfictl/blob/8c3b12965dbf2c2caa18b6a4ebd667c3a2d33108/pkg/cli/image_apk.go)

If you believe that one or more of these images cannot be safely removed, please leave a comment with a brief explanation.

Thank you in advance!

**Comment by jdolitsky** [comment]
@luhring can `coredns` in the usage be safely replaced with a different image?

**Comment by luhring** [comment]
Yeah no sweat! I'll swap it out now.

Just curious, why didn't the `cgr.dev/chainguard/prometheus-operator` reference just below trigger an issue as well?

**Comment by jdolitsky** [comment]
@luhring I think we basically need to ignore manpages somehow here: https://github.com/chainguard-dev/public-image-search/blob/main/pkg/search/github.go#L35

It seems maybe related to escaping hypens? https://github.com/wolfi-dev/wolfictl/blob/469f626a5fc7c6f482c5ef8cc484e3d0e2ad2181/docs/man/man1/wolfictl-image-apk.1#L53
