### ISSUE TITLE
create a proper release workflow

### ISSUE THREAD

**Issue by developer-guy** [wolfi-dev/wolfictl#15]
**Description**

We can use a similar approach (goreleaser for binaries, ko for OCI images) as we did in apko project.

> _https://github.com/chainguard-dev/apko/blob/main/.github/workflows/release.yaml_

PTAL @rawlingsj @Dentrax

**Comment by imjasonh** [comment]
I'm sort of on the fence. This isn't really a tool we expect to have wide usage, just folks contributing to Wolfi. It may be easier to just expect folks to stay close to `@main` and not have to bother with actual releases.

If we have a use for an OCI image we can build one from main, but I don't think we even have that need yet.

Whatever we do we should document it well in Wolfi developer docs

**Comment by developer-guy** [comment]
Thanks @imjasonh, that makes a lot of sense, I'm closing this issue.

**Comment by jdolitsky** [comment]
We do have `ghcr.io/wolfi-dev/wolfictl:latest` built nightly from main
