### ISSUE TITLE
Create GitHub Action for wolfictl

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/wolfictl#3]
**Description**

I think it would be nice to have a GitHub Action for wolfictl. I strongly believe that there will be a bunch of new subcommands in the wolfictl and people may want to use these in their pipelines in the near future. I can't list the use cases, but requirements will show the path.

An example use case: https://github.com/wolfi-dev/os/issues/278

Dropping the idea here for further discussing. Would it be too early to do this?

**Comment by rawlingsj** [comment]
I'm working on a GHA for this ATM.  Should have it done today.

**Comment by rawlingsj** [comment]
fixed https://github.com/wolfi-dev/wolfictl/blob/main/.github/actions/action.yaml,  used in this PR https://github.com/wolfi-dev/os/pull/280
