### ISSUE TITLE
wolfictl dot does not seem to work, or needs some more docs

### ISSUE THREAD

**Issue by vaikas** [wolfi-dev/wolfictl#344]
**Description**

The dot command does not seem to work as advertised here: https://github.com/wolfi-dev/wolfictl/blob/main/docs/cmd/wolfictl_dot.md

```
vaikas@vaikas-mbp os %  wolfictl dot
Error: unable to resolve needs for package ko-fips: unable to load pipeline: open pipelines/go-fips/build.yaml: file does not exist
FATA[0000] error during command execution: unable to resolve needs for package ko-fips: unable to load pipeline: open pipelines/go-fips/build.yaml: file does not exist
vaikas@vaikas-mbp os % ls -l pipelines/go-fips/build.yaml
-rw-r--r--  1 vaikas  staff  2446 Aug 11 11:56 pipelines/go-fips/build.yaml
vaikas@vaikas-mbp os % pwd
/Users/vaikas/projects/go/src/github.com/wolfi-dev/os
```

It's entirely possibly if not likely that I'm holding this wrong.

**Comment by rawlingsj** [comment]
I'm not too familiar with this command but did just notice a flag, I tested here and it's generated a list of packages

i.e. from the root of your wolfi os cloned repo...
```
wolfictl dot --pipeline-dir pipelines
```

Having said that, I just tried here after `brew install graphviz` (that took an age) and running
```
wolfictl dot --pipeline-dir pipelines | dot -Tsvg > graph.svg
```
the generated svg does not have any relationships.

@imjasonh I wonder if this command has been impacted with the package resolving work that happend a little while back?

**Comment by vaikas** [comment]
zomg!! Thanks @rawlingsj the pipeline-dir was indeed the problem.

Bit interesting that it said the file didn't exist unless you give that flag explicitly?

**Comment by rawlingsj** [comment]
yeah totally, I think `https://github.com/wolfi-dev/os/tree/main/pipelines/go-fips` was added recently.

We could add a default `pipelines` to [here](https://github.com/wolfi-dev/wolfictl/blob/931f7f711650438d6eb779356411fa87946ef1d9/pkg/cli/dot.go#L75).  

I just tried that and checked things don't break if there is no `./pipelines` dir and that's fine.  I'll PR that now but still don't know why the graphviz diagram has no relationships.
