### ISSUE TITLE
Advisory: Simplify the advisory creation flow

### ISSUE THREAD

**Issue by pdeslaur** [wolfi-dev/wolfictl#611]
**Background**

The flow of advisory data is increasingly becoming automated ([example](https://github.com/wolfi-dev/advisories/pulls?q=is:pr+is:closed+label:%22automated+pr%22)). Most of the manual changes are the results of the creation of a new package. However, instructions for creating new advisories are unclear, and the creation of advisories is very toilsome.

**Problem to solve**

Any new delivery specialist should be able to file **correct** advisories with **minimal time** that would result in the change being merged without further comment. Packagers shouldn't have to learn the ins and outs of all the advisory status. Packages shouldn't have to memorize a mental flowchart to decide the appropriate status.

**Proposal**

Create a new `wolfictl` command that would:

- Accepts the name of a new package
- Scan the main package and all sub-packages
- For each vulnerability found, ask questions to determine what to enter in the advisory. At the end of the flow, the content of the advisory file should contain accurate information.

**Comment by luhring** [comment]
I think this was completed with the addition of the `wolfictl adv guide` command and I just forgot to close this 🤦
