### ISSUE TITLE
make wolfictl go installable 

### ISSUE THREAD

**Issue by strongjz** [wolfi-dev/wolfictl#77]
make wolfictl go installable 

```
go install github.com/wolfi-dev/wolfictl@latest
go: github.com/wolfi-dev/wolfictl@latest (in github.com/wolfi-dev/wolfictl@v0.0.0-20230222175213-9c5cfe0525dc):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by imjasonh** [comment]
These are the `replace`s in question:

https://github.com/wolfi-dev/wolfictl/blob/9c5cfe0525dc7415cec482342ca674875c1e9115/go.mod#L5-L10

1. use @jdolitsky 's fork of the alpine-go package to make `generate-index` much _much_ faster
2. use github.com/n3wscott/go-graphviz which drops unneeded graphviz functionality with license issues (don't remember exactly what)
3. pin to `k8s.io/client-go v0.25.3`

The first is probably ~easy to get rid of, by just merging that work upstream.

We could drop the second if we need to, and just shell out to `graphviz`.

The third one might be harder.

**Comment by cpanato** [comment]
or we have a wofictl release 🙃

**Comment by imjasonh** [comment]
What are we trying to do?

`go install` might not work, but this should:

```
git clone --depth=1 https://github.com/wolfi-dev/wolfictl && cd wolfictl && go install
```
