### ISSUE TITLE
wolfictl not uses annotated tags for gh releases

### ISSUE THREAD

**Issue by lpcalisi** [wolfi-dev/wolfictl#844]
Hello, i'm notice that wolfictl is not using annotated tags for checking releases.
In https://github.com/wolfi-dev/os/pull/19280 i use annotated tag but then https://github.com/wolfi-dev/os/pull/19493 detect a new release with lightweight tag

In this  https://github.com/chainguard-dev/melange/pull/686 we add support for annotated tags but i think that we should make something in wolfictl with that too.

@wlynch @rawlingsj  do you think about it?

**Comment by xnox** [comment]
git-checkout tries hard to check things out. But all web UI uses commit-ids not annotated tags. Even when navigating to annotated tags.
