### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by johanneskastl** [wolfi-dev/wolfictl#869]
Hi everything,

I am packaging wolfictl for openSUSE, as I found it highly interesting and wanted to play around with it.

However, wolfictl currently does not have release, only tags. So, is there a changelog of some kind that I failed to find? Only having the list of commits is not really valuable.

Thanks in advance,
Johannes

**Comment by luhring** [comment]
Hi @johanneskastl, thanks for reaching out!

Wolfictl is _mostly_ an internal dev tool, it's not really intended for general use. If folks find it useful, that's great! But we add and remove functionality pretty often without notice, so it doesn't quite fit the profile of a typical OSS tool, and it's not something we intend to support outwardly.

I hope that makes sense!

**Comment by johanneskastl** [comment]
Sorry for the late reply, I missed your comment.

I agree that it kinda makes sense, although I think that a changelog or an automated list of changes in the release could be useful for internal users, too. Especially if functionality is added and removed...

Anyway, closing this for now.

Have a nice weekend!
